version: "3.9"

services:
  # SOURCE
  docker-migrate-source:
    image: teste
    ports:
      - 8722:22
    environment:
      - PASSWORD=s3cR3t
    volumes:
      # Add :ro to make the volumes read-only just in case
      - some-data-volume:/volumes/some-data-volume:ro
 
  # DESTINATION
  docker-migrate-destination:
    image: teste
    environment:
      - HOST=192.168.1.2 # Source host
      - PORT=8722 # Source port, 8722 is default and can be omitted    
      - PASSWORD=s3cR3t
    volumes:
      # No :ro here!
      - some-data-volume:/volumes/some-data-volume

volumes:
  # List of volumes
  some-data-volume:
    external: true